/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef map_data_structure_CONSTANTS_H
#define map_data_structure_CONSTANTS_H

#include "map_data_structure_types.h"

namespace map_thrift {

class map_data_structureConstants {
 public:
  map_data_structureConstants();

};

extern const map_data_structureConstants g_map_data_structure_constants;

} // namespace

#endif
