/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "map_data_structure_constants.h"

namespace map_thrift {

const map_data_structureConstants g_map_data_structure_constants;

map_data_structureConstants::map_data_structureConstants() {
}

} // namespace

