/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "nn_thrift_constants.h"

namespace nn_thrift {

const nn_thriftConstants g_nn_thrift_constants;

nn_thriftConstants::nn_thriftConstants() {
}

} // namespace

