/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef nn_thrift_CONSTANTS_H
#define nn_thrift_CONSTANTS_H

#include "nn_thrift_types.h"

namespace nn_thrift {

class nn_thriftConstants {
 public:
  nn_thriftConstants();

};

extern const nn_thriftConstants g_nn_thrift_constants;

} // namespace

#endif
