#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys

from thrift.transport import TTransport
all_structs = []


class NNImage(object):
    """
    Attributes:
     - width
     - height
     - channels
     - bytes
    """


    def __init__(self, width=None, height=None, channels=None, bytes=None,):
        self.width = width
        self.height = height
        self.channels = channels
        self.bytes = bytes

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I16:
                    self.width = iprot.readI16()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I16:
                    self.height = iprot.readI16()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.BYTE:
                    self.channels = iprot.readByte()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRING:
                    self.bytes = iprot.readBinary()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('NNImage')
        if self.width is not None:
            oprot.writeFieldBegin('width', TType.I16, 1)
            oprot.writeI16(self.width)
            oprot.writeFieldEnd()
        if self.height is not None:
            oprot.writeFieldBegin('height', TType.I16, 2)
            oprot.writeI16(self.height)
            oprot.writeFieldEnd()
        if self.channels is not None:
            oprot.writeFieldBegin('channels', TType.BYTE, 3)
            oprot.writeByte(self.channels)
            oprot.writeFieldEnd()
        if self.bytes is not None:
            oprot.writeFieldBegin('bytes', TType.STRING, 4)
            oprot.writeBinary(self.bytes)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        if self.width is None:
            raise TProtocolException(message='Required field width is unset!')
        if self.height is None:
            raise TProtocolException(message='Required field height is unset!')
        if self.channels is None:
            raise TProtocolException(message='Required field channels is unset!')
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(NNImage)
NNImage.thrift_spec = (
    None,  # 0
    (1, TType.I16, 'width', None, None, ),  # 1
    (2, TType.I16, 'height', None, None, ),  # 2
    (3, TType.BYTE, 'channels', None, None, ),  # 3
    (4, TType.STRING, 'bytes', 'BINARY', None, ),  # 4
)
fix_spec(all_structs)
del all_structs
