/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef voice_control_thrift_CONSTANTS_H
#define voice_control_thrift_CONSTANTS_H

#include "voice_control_thrift_types.h"

namespace control_thrift {

class voice_control_thriftConstants {
 public:
  voice_control_thriftConstants();

  std::string car26_id;
  std::string car27_id;
};

extern const voice_control_thriftConstants g_voice_control_thrift_constants;

} // namespace

#endif
