/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "voice_control_thrift_constants.h"

namespace control_thrift {

const voice_control_thriftConstants g_voice_control_thrift_constants;

voice_control_thriftConstants::voice_control_thriftConstants() {
  car26_id = "car26";

  car27_id = "car27";

}

} // namespace

